-- INTRA AURA: customer delivery profile
-- Safe to run more than once on PostgreSQL.

ALTER TABLE users ADD COLUMN IF NOT EXISTS address VARCHAR(300);
ALTER TABLE users ADD COLUMN IF NOT EXISTS area_street VARCHAR(200);
ALTER TABLE users ADD COLUMN IF NOT EXISTS landmark VARCHAR(200);
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS state VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pincode VARCHAR(6);
